### ISSUE TITLE
Can this be run in a Ubuntu VM ?

### ISSUE THREAD

**Issue by a2t2** [SamsungLabs/TwiTi#7]
I am using an Ubuntu 20.04 VM on a MAC OS machine.

I did the installation in the VM. I tried the following command:

```
$ python3 -m ner.builder
# of total sentence: 191
# of total labels: 191
GPU: cpu
Number of GPUs: 0
t_total value of -1 results in schedule not being applied
Killed
```

How can I make it work in a VM ? Thanks.

**Comment by sole2** [comment]
Hello @a2t2 
TwiTi does not have any special code that won't work in VM.
I suspect PyTorch which seems quite sensitive with environment.
https://github.com/SamsungLabs/TwiTi/blob/f17d5ca083f6f9f6e166dd4348b057bfd8df7d33/requirements.txt#L10
Could you check if PyTorch works well?

**Comment by a2t2** [comment]
Does Twiti require a GPU to run ?

**Comment by sole2** [comment]
No. GPU is not mandatory. But you may have to modify `batch_size`, `epochs` to adjust memory usage.
https://github.com/SamsungLabs/TwiTi/blob/f17d5ca083f6f9f6e166dd4348b057bfd8df7d33/ner/builder.py#L205

**Comment by a2t2** [comment]
I tried to run it on a Ubuntu PC. Is the following the expected output:
```
$ python3 -m ner.builder
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 231508/231508 [00:00<00:00, 1752987.67B/s]
# of total sentence: 190
# of total labels: 190
GPU: cpu
Number of GPUs: 0
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 407873900/407873900 [00:18<00:00, 22521675.88B/s]
t_total value of -1 results in schedule not being applied
/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha)
# of EPOCH: 0
Train loss: 0.7649931777268648
# of EPOCH: 1
Train loss: 0.10830321162939072
# of EPOCH: 2
Train loss: 0.09037258165578048
```

**Comment by a2t2** [comment]
Is this expected ?
```
$ python3 -m ioc_extractor -E ../twitter_data/test.json 
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/Twiti/TwiTi/ioc_extractor/__main__.py", line 44, in <module>
    main()
  File "/home/user/Twiti/TwiTi/ioc_extractor/__main__.py", line 32, in main
    ioc_object_list = ioc_extractor.ioc_extraction(
  File "/home/user/Twiti/TwiTi/ioc_extractor/ioc_extract_manager.py", line 77, in ioc_extraction
    orig_text = tw['full_text']
TypeError: string indices must be integers
```
test.json contains (taken from https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/overview):

```
{
  "created_at": "Thu Apr 06 15:24:15 +0000 2017",
  "id_str": "850006245121695744",
  "text": "1\/ Today we\u2019re sharing our vision for the future of the Twitter API platform!\nhttps:\/\/t.co\/XweGngmxlP",
  "user": {
    "id": 2244994945,
    "name": "Twitter Dev",
    "screen_name": "TwitterDev",
    "location": "Internet",
    "url": "https:\/\/dev.twitter.com\/",
    "description": "Your official source for Twitter Platform news, updates & events. Need technical help? Visit https:\/\/twittercommunity.com\/ \u2328\ufe0f #TapIntoTwitter"
  },
  "place": {   
  },
  "entities": {
    "hashtags": [      
    ],
    "urls": [
      {
        "url": "https:\/\/t.co\/XweGngmxlP",
        "unwound": {
          "url": "https:\/\/cards.twitter.com\/cards\/18ce53wgo4h\/3xo1c",
          "title": "Building the Future of the Twitter API Platform"
        }
      }
    ],
    "user_mentions": [     
    ]
  }
}
```

**Comment by sole2** [comment]
`ner.builder` worked well.
Expected input of `ion_extractor` is a list of tweets. So tweet object in `test.json` should wrapped with `[]`.
Furthermore tweet object seems slightly changed. `"full_text"` may have to changed to `"text"`.

**Comment by a2t2** [comment]
I replaced "full_text" with "text" in the following instances:
```
$ grep -rn 'full_text' ./
./classifier/__main__.py:29:                    text = tweet["retweeted_status"]["full_text"]
./classifier/__main__.py:31:                    text = tweet["full_text"]
./ioc_extractor/ioc_extract_manager.py:37:                    text = tweet['retweeted_status']['full_text'] if 'retweeted_status' in tweet else tweet['full_text']
./ioc_extractor/ioc_extract_manager.py:41:                            logger.info(f'dropped pastebin: {tweet["full_text"]}')
./ioc_extractor/ioc_extract_manager.py:74:                orig_text = tw['retweeted_status']['full_text']
./ioc_extractor/ioc_extract_manager.py:77:                orig_text = tw['full_text']
```

The following is the test file (I have added a md5 value in the text field):
```
[
{
  "created_at": "Thu Apr 06 15:24:15 +0000 2017",
  "id_str": "850006245121695744",
  "text": "This is a md5 value d3ffc98a624c2c4968d9dd0e29c700d5",
  "user": {
    "id": 2244994945,
    "name": "Twitter Dev",
    "screen_name": "TwitterDev",
    "location": "Internet",
    "url": "https:\/\/dev.twitter.com\/",
    "description": "Your official source for Twitter Platform news, updates & events. Need technical help? Visit https:\/\/twittercommunity.com\/ \u2328\ufe0f #TapIntoTwitter"
  },
  "place": {   
  },
  "entities": {
    "hashtags": [      
    ],
    "urls": [
      {
        "url": "https:\/\/t.co\/XweGngmxlP",
        "unwound": {
          "url": "https:\/\/cards.twitter.com\/cards\/18ce53wgo4h\/3xo1c",
          "title": "Building the Future of the Twitter API Platform"
        }
      }
    ],
    "user_mentions": [     
    ]
  }
}
]
```
Is the following the expected result:
```
$ python3 -m ioc_extractor -E ../twitter_data/test-2.json
$ cat extracted_iocs.json 
[{"iocs": {"hashes": {"sha1": [], "sha256": [], "md5": ["d3ffc98a624c2c4968d9dd0e29c700d5"]}, "ips": [], "urls": {"urls": [], "domain": []}}, "entities": [], "context": [], "externals": []}]
```

**Comment by sole2** [comment]
Yep. It is expected result. 😄

**Comment by a2t2** [comment]
Thanks for your help !
